# Generated by Django 4.2.1 on 2023-12-20 21:24

from django.db import migrations, models
import hospital_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('complaint', models.CharField(blank=True, max_length=500, validators=[hospital_app.models.RussianLettersValidator()], verbose_name='Жалобы пациента')),
                ('readings', models.TextField(blank=True, validators=[hospital_app.models.RussianLettersValidator()], verbose_name='Текст доктора')),
            ],
        ),
    ]
